services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ticketera_db
      - POSTGRES_USER=sisadmin
      - POSTGRES_PASSWORD=C0ntr@señ@_D3s@rr0ll0
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    command: >
      sh -c "
        until PGPASSWORD=$$POSTGRES_PASSWORD psql -h db -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' > /dev/null 2>&1; do
          echo 'Postgres is unavailable - sleeping'
          sleep 1
        done
        echo 'Postgres is up - executing command'
        python manage.py migrate --noinput &&
        python manage.py createsuperuser --no-input &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=ticketera_db
      - POSTGRES_USER=sisadmin
      - POSTGRES_PASSWORD=C0ntr@señ@_D3s@rr0ll0
      - SECRET_KEY=django-insecure-tu-clave-secreta-de-desarrollo-aqui
      - DEBUG=True
      - DATABASE_URL=postgres://sisadmin:C0ntr@señ@_D3s@rr0ll0@db:5432/ticketera_db
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SUPERUSER_USERNAME=sisadmin
      - DJANGO_SUPERUSER_EMAIL=soportecge141@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=C0ntr4S3n14
    depends_on:
      - db
      - redis



# --- SERVICIO DEL FRONTEND COMENTADO TEMPORALMENTE ---
  # frontend:
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  postgres_data: