version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend: # Renombrado de 'web' a 'backend' para mayor claridad
    build:
      context: ./backend
    command: ["/app/wait-for-postgres.sh", "db", "sh", "-c", "python manage.py migrate --noinput && python manage.py createsu && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - db
      - redis

  frontend: # <-- SERVICIO DEL FRONTEND AÑADIDO
    build:
      context: ./frontend
    volumes:
      # Monta el código para que los cambios se reflejen en tiempo real (hot-reloading)
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: