version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ticketera_db
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=password 
    ports:
      - "5432:5432" 

  redis: 
    image: redis:7-alpine 
    ports:
      - "6379:6379" 
  web: 
    build: . 
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - .:/app 
    ports:
      - "8000:8000" 
    environment: 
      - DATABASE_URL=postgres://user:password@db:5432/ticketera_db
      - REDIS_URL=redis://redis:6379/0 # URL de conexión a Redis
      - SECRET_KEY=your_insecure_development_secret_key 
      - DEBUG=True 
    depends_on: 
      - db
      - redis

volumes: 
  postgres_data: